version: '2.0'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
